/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUTeclado.java
 *
 * Created on 10/07/2010, 21:09:35
 */

package aifone.iu;

import javax.swing.JTextField;

/**
 *
 * @author William
 */
public class IUTeclado extends javax.swing.JPanel {

    /** Creates new form IUTeclado */
    private javax.swing.JTextField campoAlvo;
    private String texto;
    public IUTeclado() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoQ = new javax.swing.JButton();
        botaoW = new javax.swing.JButton();

        botaoQ.setText("q");
        botaoQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoQActionPerformed(evt);
            }
        });

        botaoW.setText("w");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoW)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoQ)
                    .addComponent(botaoW))
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoQActionPerformed
        adicionarCaractere("q");

    }//GEN-LAST:event_botaoQActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoQ;
    private javax.swing.JButton botaoW;
    // End of variables declaration//GEN-END:variables

    public void adicionarCaractere(String caractere){
        if( getCampoAlvo() != null)
        getCampoAlvo().setText(getCampoAlvo().getText().concat(caractere));
    }



    public JTextField getCampoAlvo() {
        return campoAlvo;
    }

    public void setCampoAlvo(JTextField campoAlvo) {
        this.campoAlvo = campoAlvo;
    }

    public String getTexto() {
        return texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }



}
