/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUTelaInicial.java
 *
 * Created on 09/07/2010, 10:36:20
 */

package aifone.iu;

import aifone.IAiFoneIU;

/**
 * 
 * @author William
 */
public class IUTelaInicial extends javax.swing.JPanel {

	private IAiFoneIU aiFone;

	/** Creates new form IUTelaInicial */
	public IUTelaInicial(IAiFoneIU aiFone) {
		initComponents();
		this.aiFone = aiFone;
		labelNumero.setText(this.aiFone.getTelefone().getNumero());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		botaoIniciarTelefone = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		labelNumero = new javax.swing.JLabel();

		setPreferredSize(new java.awt.Dimension(320, 480));

		botaoIniciarTelefone.setText("Telefone");
		botaoIniciarTelefone
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						botaoIniciarTelefoneMouseClicked(evt);
					}
				});

		jButton1.setText("HiTwitter");

		jLabel1.setText("AiFone");

		labelNumero.setText("meuNumero");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(138,
																		138,
																		138)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.CENTER)
																				.addComponent(
																						labelNumero)
																				.addComponent(
																						jLabel1)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(117,
																		117,
																		117)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						botaoIniciarTelefone)
																				.addComponent(
																						jButton1))))
								.addContainerGap(125, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(64, 64, 64)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(labelNumero)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										108, Short.MAX_VALUE)
								.addComponent(botaoIniciarTelefone)
								.addGap(42, 42, 42).addComponent(jButton1)
								.addGap(186, 186, 186)));
	}// </editor-fold>//GEN-END:initComponents

	private void botaoIniciarTelefoneMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoIniciarTelefoneMouseClicked

		aiFone.abrirTelaTelefone();

	}// GEN-LAST:event_botaoIniciarTelefoneMouseClicked

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton botaoIniciarTelefone;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel labelNumero;
	// End of variables declaration//GEN-END:variables

}
