/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUTeclado.java
 *
 * Created on 10/07/2010, 21:09:35
 */

package aifone.iu;

import javax.swing.text.JTextComponent;

/**
 * 
 * @author William
 */
public class IUTeclado extends javax.swing.JPanel {

	/** Creates new form IUTeclado */
	private IObservaTeclado campoAlvo;

	public IUTeclado() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		botaoQ = new javax.swing.JButton();
		botaoE = new javax.swing.JButton();
		botaoR = new javax.swing.JButton();
		botaoT = new javax.swing.JButton();
		botaoY = new javax.swing.JButton();
		botaoU = new javax.swing.JButton();
		botaoI = new javax.swing.JButton();
		botaoO = new javax.swing.JButton();
		botaoP = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		botaoW = new javax.swing.JButton();
		botaoA = new javax.swing.JButton();
		botaoS = new javax.swing.JButton();
		botaoD = new javax.swing.JButton();
		botaoF = new javax.swing.JButton();
		botaoG = new javax.swing.JButton();
		botaoH = new javax.swing.JButton();
		botaoJ = new javax.swing.JButton();
		botaoK = new javax.swing.JButton();
		botaoL = new javax.swing.JButton();
		botaoZ = new javax.swing.JButton();
		jButton30 = new javax.swing.JButton();
		botaoC = new javax.swing.JButton();
		botaoV = new javax.swing.JButton();
		botaoB = new javax.swing.JButton();
		botaoM = new javax.swing.JButton();
		botaoN = new javax.swing.JButton();
		botaoEspaco = new javax.swing.JButton();
		botaoApagar = new javax.swing.JButton();
		botaoX = new javax.swing.JButton();

		botaoQ.setText("Q");
		botaoQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoQActionPerformed(evt);
			}
		});

		botaoE.setText("E");
		botaoE.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoEActionPerformed(evt);
			}
		});

		botaoR.setText("R");
		botaoR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoRActionPerformed(evt);
			}
		});

		botaoT.setText("T");
		botaoT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoTActionPerformed(evt);
			}
		});

		botaoY.setText("Y");
		botaoY.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoYActionPerformed(evt);
			}
		});

		botaoU.setText("U");
		botaoU.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoUActionPerformed(evt);
			}
		});

		botaoI.setText("I");
		botaoI.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoIActionPerformed(evt);
			}
		});

		botaoO.setText("O");
		botaoO.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoOActionPerformed(evt);
			}
		});

		botaoP.setText("P");
		botaoP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoPActionPerformed(evt);
			}
		});

		jButton8.setText("1");

		jButton9.setText("2");

		jButton10.setText("3");

		jButton11.setText("4");

		jButton12.setText("5");

		jButton13.setText("6");

		jButton14.setText("7");

		jButton15.setText("8");

		jButton16.setText("9");

		jButton17.setText("0");

		botaoW.setText("W");
		botaoW.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoWActionPerformed(evt);
			}
		});

		botaoA.setText("A");
		botaoA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoAActionPerformed(evt);
			}
		});

		botaoS.setText("S");
		botaoS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoSActionPerformed(evt);
			}
		});

		botaoD.setText("D");
		botaoD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoDActionPerformed(evt);
			}
		});

		botaoF.setText("F");
		botaoF.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoFActionPerformed(evt);
			}
		});

		botaoG.setText("G");
		botaoG.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoGActionPerformed(evt);
			}
		});

		botaoH.setText("H");
		botaoH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoHActionPerformed(evt);
			}
		});

		botaoJ.setText("J");
		botaoJ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoJActionPerformed(evt);
			}
		});

		botaoK.setText("K");
		botaoK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoKActionPerformed(evt);
			}
		});

		botaoL.setText("L");
		botaoL.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoLActionPerformed(evt);
			}
		});

		botaoZ.setText("Z");
		botaoZ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoZActionPerformed(evt);
			}
		});

		jButton30.setText("X");

		botaoC.setText("C");
		botaoC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoCActionPerformed(evt);
			}
		});

		botaoV.setText("V");
		botaoV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoVActionPerformed(evt);
			}
		});

		botaoB.setText("B");
		botaoB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoBActionPerformed(evt);
			}
		});

		botaoM.setText("M");
		botaoM.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoMActionPerformed(evt);
			}
		});

		botaoN.setText("N");
		botaoN.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoNActionPerformed(evt);
			}
		});

		botaoEspaco.setText("Espaço");
		botaoEspaco.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoEspacoActionPerformed(evt);
			}
		});

		botaoApagar.setText("<");
		botaoApagar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoApagarActionPerformed(evt);
			}
		});

		botaoX.setText("X");
		botaoX.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoXActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton13)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton14)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton15)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton16)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton17))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton8)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton9)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton10)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton11)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton12)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		botaoApagar))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(45, 45,
																		45)
																.addComponent(
																		botaoM)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		botaoEspaco))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		botaoA)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		botaoS)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		botaoD)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		botaoF)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		botaoG))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														botaoZ)
																												.addComponent(
																														jButton30))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoX))
																				.addComponent(
																						botaoH))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										botaoJ)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoK)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoL))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										botaoC)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoV)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoB)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoN))))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		botaoQ)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										botaoU)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoI)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoO)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoP))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										botaoW)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoR)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoT)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										botaoY)))))
								.addContainerGap(255, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton8)
												.addComponent(jButton9)
												.addComponent(jButton12)
												.addComponent(jButton11)
												.addComponent(jButton10)
												.addComponent(botaoApagar))
								.addGap(7, 7, 7)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton14)
												.addComponent(jButton15)
												.addComponent(jButton16)
												.addComponent(jButton17)
												.addComponent(jButton13))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														botaoQ,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														23,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(botaoW)
												.addComponent(botaoT)
												.addComponent(botaoE)
												.addComponent(botaoR)
												.addComponent(botaoY))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(botaoP)
												.addComponent(botaoO)
												.addComponent(botaoI)
												.addComponent(botaoU))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(botaoA)
												.addComponent(botaoS)
												.addComponent(botaoD)
												.addComponent(botaoF)
												.addComponent(botaoG))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(botaoJ)
												.addComponent(botaoK)
												.addComponent(botaoL)
												.addComponent(botaoH))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(botaoZ)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jButton30)
																.addComponent(
																		botaoC)
																.addComponent(
																		botaoV)
																.addComponent(
																		botaoB)
																.addComponent(
																		botaoX)
																.addComponent(
																		botaoN)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														botaoEspaco,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														23,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(botaoM))
								.addContainerGap(211, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void botaoQActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoQActionPerformed
		adicionarCaractere("q");

	}// GEN-LAST:event_botaoQActionPerformed

	private void botaoRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoRActionPerformed
		adicionarCaractere("r");
	}// GEN-LAST:event_botaoRActionPerformed

	private void botaoTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoTActionPerformed
		adicionarCaractere("t");
	}// GEN-LAST:event_botaoTActionPerformed

	private void botaoUActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoUActionPerformed
		adicionarCaractere("u");
	}// GEN-LAST:event_botaoUActionPerformed

	private void botaoWActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoWActionPerformed
		adicionarCaractere("w");
	}// GEN-LAST:event_botaoWActionPerformed

	private void botaoEActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEActionPerformed
		adicionarCaractere("e");
	}// GEN-LAST:event_botaoEActionPerformed

	private void botaoYActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoYActionPerformed
		adicionarCaractere("y");
	}// GEN-LAST:event_botaoYActionPerformed

	private void botaoIActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoIActionPerformed
		adicionarCaractere("i");
	}// GEN-LAST:event_botaoIActionPerformed

	private void botaoOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoOActionPerformed
		adicionarCaractere("o");
	}// GEN-LAST:event_botaoOActionPerformed

	private void botaoPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoPActionPerformed
		adicionarCaractere("p");
	}// GEN-LAST:event_botaoPActionPerformed

	private void botaoAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoAActionPerformed
		adicionarCaractere("a");
	}// GEN-LAST:event_botaoAActionPerformed

	private void botaoSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoSActionPerformed
		adicionarCaractere("s");
	}// GEN-LAST:event_botaoSActionPerformed

	private void botaoDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoDActionPerformed
		adicionarCaractere("d");
	}// GEN-LAST:event_botaoDActionPerformed

	private void botaoFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoFActionPerformed
		adicionarCaractere("f");
	}// GEN-LAST:event_botaoFActionPerformed

	private void botaoGActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoGActionPerformed
		adicionarCaractere("g");
	}// GEN-LAST:event_botaoGActionPerformed

	private void botaoHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoHActionPerformed
		adicionarCaractere("h");
	}// GEN-LAST:event_botaoHActionPerformed

	private void botaoJActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoJActionPerformed
		adicionarCaractere("j");
	}// GEN-LAST:event_botaoJActionPerformed

	private void botaoKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoKActionPerformed
		adicionarCaractere("k");
	}// GEN-LAST:event_botaoKActionPerformed

	private void botaoLActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoLActionPerformed
		adicionarCaractere("l");
	}// GEN-LAST:event_botaoLActionPerformed

	private void botaoZActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoZActionPerformed
		adicionarCaractere("z");
	}// GEN-LAST:event_botaoZActionPerformed

	private void botaoXActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoXActionPerformed
		adicionarCaractere("x");
	}// GEN-LAST:event_botaoXActionPerformed

	private void botaoCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoCActionPerformed
		adicionarCaractere("c");
	}// GEN-LAST:event_botaoCActionPerformed

	private void botaoVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoVActionPerformed
		adicionarCaractere("v");
	}// GEN-LAST:event_botaoVActionPerformed

	private void botaoBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoBActionPerformed
		adicionarCaractere("b");
	}// GEN-LAST:event_botaoBActionPerformed

	private void botaoMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoMActionPerformed
		adicionarCaractere("m");
	}// GEN-LAST:event_botaoMActionPerformed

	private void botaoNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoNActionPerformed
		adicionarCaractere("n");
	}// GEN-LAST:event_botaoNActionPerformed

	private void botaoEspacoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEspacoActionPerformed
		adicionarCaractere(" ");
	}// GEN-LAST:event_botaoEspacoActionPerformed

	private void botaoApagarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoApagarActionPerformed
		if (getCampoAlvo() != null) {
			//String texto = getCampoAlvo().getText();
			//getCampoAlvo().setText(texto.substring(0, texto.length() - 1));
			getCampoAlvo().apagar();
		}

	}// GEN-LAST:event_botaoApagarActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton botaoA;
	private javax.swing.JButton botaoApagar;
	private javax.swing.JButton botaoB;
	private javax.swing.JButton botaoC;
	private javax.swing.JButton botaoD;
	private javax.swing.JButton botaoE;
	private javax.swing.JButton botaoEspaco;
	private javax.swing.JButton botaoF;
	private javax.swing.JButton botaoG;
	private javax.swing.JButton botaoH;
	private javax.swing.JButton botaoI;
	private javax.swing.JButton botaoJ;
	private javax.swing.JButton botaoK;
	private javax.swing.JButton botaoL;
	private javax.swing.JButton botaoM;
	private javax.swing.JButton botaoN;
	private javax.swing.JButton botaoO;
	private javax.swing.JButton botaoP;
	private javax.swing.JButton botaoQ;
	private javax.swing.JButton botaoR;
	private javax.swing.JButton botaoS;
	private javax.swing.JButton botaoT;
	private javax.swing.JButton botaoU;
	private javax.swing.JButton botaoV;
	private javax.swing.JButton botaoW;
	private javax.swing.JButton botaoX;
	private javax.swing.JButton botaoY;
	private javax.swing.JButton botaoZ;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton30;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;

	// End of variables declaration//GEN-END:variables

	public void adicionarCaractere(String caractere) {
		if (getCampoAlvo() != null)
			getCampoAlvo().inserirCaractere(caractere);
			//getCampoAlvo().setText(getCampoAlvo().getText().concat(caractere));
	}

	public IObservaTeclado getCampoAlvo() {
		return campoAlvo;
	}

	public void setCampoAlvo(IObservaTeclado campoAlvo) {
		this.campoAlvo = campoAlvo;
	}

}
