/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUTelaInicial.java
 *
 * Created on 09/07/2010, 10:36:20
 */

package aifone.iu;

import aifone.AiFone;

/**
 * 
 * @author William
 */
public class IUTelaInicial extends javax.swing.JPanel {

	private AiFone aiFone;

	/** Creates new form IUTelaInicial */
	public IUTelaInicial(AiFone aiFone) {
		initComponents();
		this.aiFone = aiFone;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		botaoIniciarTelefone = new javax.swing.JButton();

		setPreferredSize(new java.awt.Dimension(320, 480));

		botaoIniciarTelefone.setText("Telefone");
		botaoIniciarTelefone
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						botaoIniciarTelefoneMouseClicked(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(94, 94, 94).addComponent(
						botaoIniciarTelefone).addContainerGap(151,
						Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(350,
						Short.MAX_VALUE).addComponent(botaoIniciarTelefone)
						.addGap(107, 107, 107)));
	}// </editor-fold>//GEN-END:initComponents

	private void botaoIniciarTelefoneMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botaoIniciarTelefoneMouseClicked

		IUContainer.getInstance().setPanel(aiFone.getIUDiscarInstance(this));

	}// GEN-LAST:event_botaoIniciarTelefoneMouseClicked

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton botaoIniciarTelefone;
	// End of variables declaration//GEN-END:variables

}
