/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IULerTweets.java
 *
 * Created on 13/07/2010, 02:31:25
 */

package aifone.hitwitter.iu;

import java.rmi.RemoteException;

import aifone.IAiFoneIU;
import aifone.hitwitter.AppHiTwitter;
import aifone.hitwitter.rn.HiTwitter;
import aifone.hitwitter.rn.Tweet;

/**
 *
 * @author William
 */
public class IULerTweets extends javax.swing.JPanel {

	private AppHiTwitter appHiTwitter;
	private HiTwitter hiTwitter;
	
    public IULerTweets(AppHiTwitter appHiTwitter, HiTwitter hiTwitter) {
    	this.appHiTwitter = appHiTwitter;
    	this.hiTwitter = hiTwitter;
        initComponents();
        String text = "";
        try {
			for( Tweet tweet:hiTwitter.getTweets() ){
				text += tweet.getAutor() + "\n" + tweet.getConteudo() + "\n\n\n";
			}
		} catch (RemoteException e) {
			e.printStackTrace();
		}
        jTextArea1.setText(text);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoNovoTweet = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        botaoNovoTweet.setText("Novo Tweet!");
        botaoNovoTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoTweetActionPerformed(evt);
            }
        });

        botaoSair.setText("X");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoNovoTweet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(botaoSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoNovoTweet)
                    .addComponent(botaoSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoTweetActionPerformed
    	appHiTwitter.abrirTelaEnviarTweet();
    }//GEN-LAST:event_botaoNovoTweetActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        appHiTwitter.voltarTelaInicial();
    }//GEN-LAST:event_botaoSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoNovoTweet;
    private javax.swing.JButton botaoSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
