/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUConversa.java
 *
 * Created on 09/07/2010, 16:33:37
 */

package aifone.telefone.iu;

import javax.swing.JScrollBar;
import javax.swing.JTextArea;

import aifone.telefone.AppTelefone;
import aifone.telefone.IAppTelefone;
import aifone.telefone.rn.RNAppTelefone;
import entidades.Mensagem;
import entidades.Telefone;

/**
 * 
 * @author William
 */
public class IUConversa extends javax.swing.JPanel {

	private RNAppTelefone rnAppTelefone;
	private IAppTelefone appTelefone;

	/** Creates new form IUConversa */
	public IUConversa(AppTelefone appTelefone, RNAppTelefone rnAppTelefone) {
		initComponents();
		this.rnAppTelefone = rnAppTelefone;
		this.appTelefone = appTelefone;
		componenteTeclado.setCampoAlvo(campoMensagem);
		areaConversa.setWrapStyleWord(true);
		areaConversa.setLineWrap(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iUTeclado1 = new aifone.iu.IUTeclado();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaConversa = new javax.swing.JTextArea();
        campoMensagem = new javax.swing.JTextField();
        botaoEnviar = new javax.swing.JButton();
        componenteTeclado = new aifone.iu.IUTeclado();
        botaoSair = new javax.swing.JButton();

        areaConversa.setColumns(20);
        areaConversa.setRows(5);
        jScrollPane1.setViewportView(areaConversa);

        campoMensagem.setText(" ");

        botaoEnviar.setText("Enviar!");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        botaoSair.setText("X");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componenteTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(campoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoEnviar))
                            .addComponent(botaoSair))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(botaoSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEnviar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componenteTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
            appTelefone.abrirTelaInicial();
            rnAppTelefone.encerrarChamada();
        }//GEN-LAST:event_botaoSairActionPerformed

	private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEnviarActionPerformed
            enviarMensagem();
	}

        public void exibirMensagem(String numero, Mensagem mensagem){
            String frase = mensagem.getConteudo();
            String conversa = areaConversa.getText();
			areaConversa.setText(conversa.concat("<"+numero+"> "+frase + "\n"));
			areaConversa.setCaretPosition(areaConversa.getDocument().getLength());
        }

        private void enviarMensagem(){
            String frase = campoMensagem.getText();
            Mensagem mensagem = new Mensagem(frase);
            rnAppTelefone.enviarMensagem(mensagem);
            campoMensagem.setText("");
            exibirMensagem(appTelefone.getTelefone().getNumero(), mensagem);
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaConversa;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoMensagem;
    private aifone.iu.IUTeclado componenteTeclado;
    private aifone.iu.IUTeclado iUTeclado1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
