/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUEfetuandoChamada.java
 *
 * Created on 09/07/2010, 15:42:38
 */

package aifone.telefone.iu;

import aifone.iu.IUContainer;

/**
 *
 * @author William
 */
public class IUEfetuandoChamada extends javax.swing.JPanel {

    /** Creates new form IUEfetuandoChamada */
    public IUEfetuandoChamada( String numero) {
        initComponents();
        labelNumero.setText(numero);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Efetuando Chamada!");

        labelNumero.setText("0000");

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelNumero)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(labelNumero)
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IUContainer.getInstance().setPanel(new IUDiscar());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNumero;
    // End of variables declaration//GEN-END:variables

}
